### ISSUE TITLE
Mod Request: ProjectE

### ISSUE THREAD

**Issue by nullifiedcat** [MinecraftModDevelopment/New-MMD-Public-Pack#63]
https://minecraft.curseforge.com/projects/projecte

I know that it's super OP, but without it or Agricraft (and magical crops compat), Avaritia is pretty much unreachable without completely destroying the server with laggy farms. For example to get Diamond Singularity, you have to harvest 18300 blocks * 9 gems * 9 essence = 1482300 Diamond Essence using regular farms, and there are 16 types of singularities, and 11 singularities are required for every Infinity Ingot. 

Maybe make ProjectE philosopher stone recipe gated behind awakened draconium or even chaos shards, but I think it should be in the pack.

**Comment by ProxyNeko** [comment]
Since this is @Morpheus1101's mod I would leave it up to him but I'm of mixed minds here

This is a kitchen sink pack anyway so for that reason I would say "eh whatever throw it in" but at the same time I don't want it to be something people can just go and win instantly.

However if a lot of the harder to get things in other mods are not going to be trickier to get *looks at Morph and his crafting table* then I think I would be fine with this.

The final choice is up to Morph and car but those are my thoughts on it at least
Approved if steps are made to be slightly harder for some mods.

**Comment by carstorm** [comment]
Even with map resets being every 6-12+ months, unless you are always on it would be impossible to reach end game for most mods so agree that this mod would be useful. I approve as long as the mod is properly gated so that you can't easily get to endgame projectE in just a few days like you can with the base setting/setup of the mod. 

I would also like to note that if we wanted to, we could use custom items/blocks using just Content Tweaker.

**Comment by nullifiedcat** [comment]
Why is avaritia in the pack then if it isn't supposed to be reachable?

**Comment by carstorm** [comment]
Was that comment directed at me. I was acknowledging that's an issue and saying that ProjectE could be used to alleviate said issue but would have to be done in such a way to not make it too easy.

**Comment by Morpheus1101** [comment]
It is in the pack for those players like myself who hammer to End Game really fast and gives us something to work towards.  It is indeed quite achievable and lots of users have gotten to use it, but as you say it is tailored towards the hardcore players who are on quite a lot, but even then it snot un-obtainable

**Comment by Morpheus1101** [comment]
I agree with adding this :D

**Comment by nullifiedcat** [comment]
What exactly needs to be tweaked - the recipes in ProjectE or adding custom EMC values?

**Comment by carstorm** [comment]
I was thinking more the recipes, specially the philosopher's stone since that's needed early game(within the mod). We could do EMC values also though that would be a lot more work and more likely to cause unintended "balance" issues.

**Comment by ProxyNeko** [comment]
Mod in pack with tweaks.
