### ISSUE TITLE
[Suggestion]Community Mod

### ISSUE THREAD

**Issue by enderger** [MinecraftModDevelopment/New-MMD-Public-Pack#71]
The community mod would be a compilation of ideas from the server players and set up by the community on the discord server. Once stable, it would be compiled, released on curseforge, and used in the modpack

**Comment by carstorm** [comment]
While I like the idea in theory, in reality it seems quite complicated and time consuming to pull off.

If members of the server wanted to brainstorm a mod and then request the specific mod be added that's fine but I personally don't feel like the staff should dedicate time and resources to help spearhead this at the current moment.

**Comment by ProxyNeko** [comment]
This is something you should talk to the other players about then collectively write up the idea and request in the correct channel in the MMD Discord server rather than ask us to do.

As carstorm says we don't have a lot of time to work on things like this especially those of us who have the server, our own mods and jobs taking over our busy lives so I think it best to talk to your fellow players and make it a community driven project, not staff made.
