### ISSUE TITLE
Administrative Request: Removing EMC values

### ISSUE THREAD

**Issue by TheSpicePhantom** [MinecraftModDevelopment/New-MMD-Public-Pack#74]
Avaritia:
- EVERYTHING as its supposed to be hard to obtain (late-game)

Draconic Evolution:
- Chaotic Cores
- Awakened Draconium
- Draconium Infused Obsidian
- Celestial Manipulator

Forestry:
- Saplings
- Fruits
Its just normal trees...

Extra:
Why does 1 block of coal only have 576 emc where coal got 128?
128*9 = 1152

https://github.com/MinecraftModDevelopment/New-MMD-Public-Pack/blob/dev/config/ProjectE/custom_emc.json

**Comment by carstorm** [comment]
In short, I decline this request.

ProjectE was added for the people who don't play everyday all day so they can get close to end game still. ProjectE power flowers aren't the fastest so this is mainly for people who don't play all that much who have their power flower chunk loaded. Also since the mod was gated it still takes time to get into the mod.

Avaritia, see above.
DE See above.
Forestry, iirc these have values added by default. Since they are so easy to get, I see no issues with the values remaining,
Extra, Either someone for some reason manually assigned the incorrect value, or there is some way to make coal that uses something of  a much smaller emc value. This is something worth looking into and fixing if it is incorrect.

**Comment by Morpheus1101** [comment]
Imho, coal is the only thing worth looking into, the Avaritia stuff that has values is using nothing of any significance to be of real help in gaining any of the items etc from the mod, ultimately i agree with car.

**Comment by ProxyNeko** [comment]
This has been discussed internally and coal will be fixed in the next push/release.
